"""initial

Revision ID: 17138dc82aa1
Revises: 
Create Date: 2023-02-06 11:31:24.815588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17138dc82aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('descr', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('category_id', sa.SMALLINT(), nullable=False),
    sa.Column('release_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('poster', sa.VARCHAR(length=512), nullable=False),
    sa.Column('kp_rating', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('imdb_rating', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    op.drop_table('categories')
    # ### end Alembic commands ###
